# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e58a67dffef316b104407023da4d89f8c8362daf8784d46611c0d1035ff4ecf000534025fd3e770535d66e709f4157feeda78c4c2769ae350ed49fc6241f0d

test:
  secret_key_base: cb13f3ec7a4244ba53a070906e849823ad69c5a5e3c4cc16910ce40d181e46ad0065e619ae2fb5b415bdf2f175a55904d01087557ca51685723df3229abb791a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
